### PR TITLE
ADD USB Code Update enable/disable

### PR DESCRIPTION
**Pull request by ChicagoDuan**
phosphor_usb_code_update is an application that use USB to do FW
update. phosphor_usb_code_update service is not a daemon, but an app
that will be called after inserting a USB flash disk.

This commit creates an object of phosphor_usb_code_update when
phosphor_usb_code_update is not started. We can enable/disable
phosphor_usb_code_update by setting the "Enabled" property to
true/false.

Please configure the “usb-code-update” option in your bb/bbappend to
enable this feature.

srvcfg_manager don't need to do anything to systemd when we
enable/disable phosphor_usb_code_update, which is different from other
services. We only need to show the "Enabled" property on the object.

When phosphor_usb_code_update is started, it will look for the
"Enabled" property of the object. If the "Enabled" property is
false, it will terminate usb code update.

The commits of phosphor_usb_code_update is:
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-bmc-code-mgmt/+/48742/1

Test:
get "Enabled" property：
busctl get-property xyz.openbmc_project.Control.Service.Manager
/xyz/openbmc_project/control/service/phosphor_2dusb_2dcode_2dupdate
xyz.openbmc_project.Control.Service.Attributes Enabled
b true

set "Enabled" property to false:
busctl set-property xyz.openbmc_project.Control.Service.Manager
/xyz/openbmc_project/control/service/phosphor_2dusb_2dcode_2dupdate
xyz.openbmc_project.Control.Service.Attributes Enabled b false

busctl get-property xyz.openbmc_project.Control.Service.Manager
/xyz/openbmc_project/control/service/phosphor_2dusb_2dcode_2dupdate
xyz.openbmc_project.Control.Service.Attributes Enabled
b false

The "Enabled" property will be persisted，reboot the BMC, then get the
"Enabled" property：
busctl get-property xyz.openbmc_project.Control.Service.Manager
/xyz/openbmc_project/control/service/phosphor_2dusb_2dcode_2dupdate
xyz.openbmc_project.Control.Service.Attributes Enabled
b false

Signed-off-by: Chicago Duan <duanzhijia01@inspur.com>
Change-Id: Iba7ffb541628d563e2c54c3e1c8c4dbe85f1507b

### CODE REVIEW

**Comment by geissonator** [comment]
jenkins run tests please

**Comment by ghost** [comment]
> jenkins run tests please

Thanks @geissonator!

**Comment by geissonator** [comment]
Please remember to link to the upstream gerrit review @ChicagoDuan. Looks like it's https://gerrit.openbmc-project.xyz/c/openbmc/service-config-manager/+/48780

**Comment by ghost** [comment]
@geissonator neither I or  @ChicagoDuan can add Reviewers, am I doing something wrong?
Thanks!

**Comment by geissonator** [comment]
> @geissonator neither I or @ChicagoDuan can add Reviewers, am I doing something wrong? Thanks!

When a new repo is added, an admin needs to add the repo to the IBM dev team. You should have permission now Bruce.

**Comment by ghost** [comment]
Thank you @geissonator !

**Comment by ChicagoDuan** [comment]
> Please remember to link to the upstream gerrit review @ChicagoDuan. Looks like it's https://gerrit.openbmc-project.xyz/c/openbmc/service-config-manager/+/48780

Okay. Thanks.

**Comment by ghost** [comment]
@ChicagoDuan please check updated comments on your Gerrit review.  Thanks!
48780: ADD USB Code Update enable/disable
https://gerrit.openbmc-project.xyz/c/openbmc/service-config-manager/+/48780

**Comment by ChicagoDuan** [comment]
>

**Comment by ChicagoDuan** [comment]
> @ChicagoDuan please check updated comments on your Gerrit review. Thanks! 48780: ADD USB Code Update enable/disable https://gerrit.openbmc-project.xyz/c/openbmc/service-config-manager/+/4878Done. 

Done. Thanks!  I see that Adriana has given +1

**Comment by ghost** [comment]
> > @ChicagoDuan please check updated comments on your Gerrit review. Thanks! 48780: ADD USB Code Update enable/disable https://gerrit.openbmc-project.xyz/c/openbmc/service-config-manager/+/4878Done.
> 
> Done. Thanks! I see that Adriana has given +1

@ChicagoDuan and have you refreshed this PR?

Thanks!

**Comment by ChicagoDuan** [comment]
> @ChicagoDuan and have you refreshed this PR?

Yes, I have refreshed this PR

**Review by anoo1 — APPROVED** [review]
Tested that symlink was created when property set to False and deleted when set to True.

**Pull request merged**
